Repository hazelcast/hazelcast-jet-contrib, pull requests merged in 2020-03, with the labels that each got.

#50 Update to 4.0
  build.gradle
Labels: follow-upstream-changes

#47 Update README and the test
  debezium/README.md
  debezium/src/test/java/com/hazelcast/jet/contrib/debezium/MySqlIntegrationTest.java
Labels: enhancement

#49 Add XA tests
  README.md
  settings.gradle
  twitter/README.md
  xa-test/README.md
  xa-test/build.gradle
  xa-test/gradle.properties
  xa-test/src/main/java/com/hazelcast/jet/contrib/xatests/JdbcXaTest.java
  xa-test/src/main/java/com/hazelcast/jet/contrib/xatests/JmsXaTest.java
  xa-test/src/main/java/com/hazelcast/jet/contrib/xatests/MyXid.java
  xa-test/src/main/java/com/hazelcast/jet/contrib/xatests/package-info.java
Labels: new module

#51 Update xa-tests readme
  xa-test/README.md
Labels: enhancement

#61 Fix zero-length branch qualifier
  xa-test/README.md
  xa-test/src/main/java/com/hazelcast/jet/contrib/xatests/MyXid.java
Labels: bug

#59 Add Spring Boot Starter for Hazelcast Jet
  README.md
  config/checkstyle/suppressions.xml
  hazelcast-jet-spring-boot-starter/README.md
  hazelcast-jet-spring-boot-starter/build.gradle
  hazelcast-jet-spring-boot-starter/gradle.properties
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/actuate/HazelcastJetHealthIndicator.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/actuate/autoconfigure/HazelcastJetHealthIndicatorAutoConfiguration.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/actuate/autoconfigure/package-info.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/actuate/package-info.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetAutoConfiguration.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetClientConfigAvailableCondition.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetClientConfiguration.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetClientProperties.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetConfigAvailableCondition.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetConfigResourceCondition.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetProperties.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetServerConfiguration.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/package-info.java
  hazelcast-jet-spring-boot-starter/src/main/resources/META-INF/spring.factories
  hazelcast-jet-spring-boot-starter/src/test/java/com/hazelcast/jet/contrib/actuate/HazelcastJetHealthIndicatorTests.java
  hazelcast-jet-spring-boot-starter/src/test/java/com/hazelcast/jet/contrib/actuate/autoconfigure/HazelcastJetHealthContributorAutoConfigurationIntegrationTests.java
  hazelcast-jet-spring-boot-starter/src/test/java/com/hazelcast/jet/contrib/actuate/autoconfigure/HazelcastJetHealthContributorAutoConfigurationTests.java
  hazelcast-jet-spring-boot-starter/src/test/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetAutoConfigurationClientTests.java
  hazelcast-jet-spring-boot-starter/src/test/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetAutoConfigurationServerTests.java
  hazelcast-jet-spring-boot-starter/src/test/resources/com/hazelcast/jet/contrib/autoconfigure/hazelcast-jet-client-specific.xml
  hazelcast-jet-spring-boot-starter/src/test/resources/com/hazelcast/jet/contrib/autoconfigure/hazelcast-jet-client-specific.yaml
  hazelcast-jet-spring-boot-starter/src/test/resources/com/hazelcast/jet/contrib/autoconfigure/hazelcast-jet-specific.xml
  hazelcast-jet-spring-boot-starter/src/test/resources/com/hazelcast/jet/contrib/autoconfigure/hazelcast-jet-specific.yaml
  hazelcast-jet-spring-boot-starter/src/test/resources/hazelcast-jet.yaml
  settings.gradle
Labels: new module

#64 rename config property of spring-boot-starter
  hazelcast-jet-spring-boot-starter/README.md
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetClientConfigAvailableCondition.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetClientProperties.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetConfigAvailableCondition.java
  hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetProperties.java
  hazelcast-jet-spring-boot-starter/src/test/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetAutoConfigurationClientTests.java
  hazelcast-jet-spring-boot-starter/src/test/java/com/hazelcast/jet/contrib/autoconfigure/HazelcastJetAutoConfigurationServerTests.java
Labels: enhancement

#65 Simplify usage of xa-test with example brokers
  xa-test/build.gradle
  xa-test/src/main/java/com/hazelcast/jet/contrib/xatests/JdbcXaTest.java
  xa-test/src/main/java/com/hazelcast/jet/contrib/xatests/JmsXaTest.java
Labels: enhancement
